name: major-minor-tag-calculator
description: Calculate major and minor semver tags, e.g. for tagging containers
author: Simon Li
inputs:
  githubToken:
    required: true
    description: GitHub token
outputs:
  tags:
    description: List of calculated tags
runs:
  using: node12
  main: dist/index.js
