name: test-and-update
on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - "*"

jobs:
  test-and-update:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      # Runs format, updates dist, runs tests
      - run: |
          npm run all
          git diff
      - uses: stefanzweifel/git-auto-commit-action@5dd17c3b53a58c1cb5eaab903826abe94765ccd6
        with:
          commit_message: "[update-dist-bot] auto-format and update dist"
          commit_user_name: update-dist-bot
          commit_user_email: update-dist-bot@example.org
          commit_author: "update-dist-bot <update-dist-bot@example.org>"
